# Generated by Django 5.1.7 on 2025-05-05 16:50

import common.apps.utils.user_directory._user_directory_path
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('music', models.FileField(blank=True, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_music_path)),
                ('view', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True)),
                ('display_time', models.IntegerField(default=10, help_text='Time in seconds to display each image')),
                ('music_preference', models.CharField(blank=True, max_length=255)),
                ('meta_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('personal', 'Personal'), ('shared', 'Shared'), ('meta', 'Meta')], default='personal', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_image_path)),
                ('image_id', models.CharField(max_length=255, unique=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('music', models.FileField(blank=True, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_music_path)),
                ('view', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('view', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_images', to='gallery.collection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_collections', to='gallery.image')),
            ],
            options={
                'verbose_name': 'Collection Image',
                'verbose_name_plural': 'Collection Images',
                'db_table': 'collection_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImageInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('favorite', 'Favorite')], max_length=10)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='gallery.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Interaction',
                'verbose_name_plural': 'Image Interactions',
                'db_table': 'image_interactions',
            },
        ),
        migrations.CreateModel(
            name='MetaComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Comment',
                'verbose_name_plural': 'Meta Comments',
                'db_table': 'meta_comments',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_audio_path)),
                ('view', models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('transcript_url', models.URLField(blank=True, null=True)),
                ('transcript_status', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=255, null=True)),
                ('transcript_insights', models.JSONField(blank=True, help_text='Full analysis results as JSON', null=True)),
                ('transcript_summary', models.TextField(blank=True, help_text='Summary of the transcript', null=True)),
                ('transcript_sentiment', models.CharField(blank=True, help_text='Overall sentiment of the transcript', max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the audio was last processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of retries for failed processing')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
                'db_table': 'audios',
                'indexes': [models.Index(fields=['uploaded_by'], name='audios_uploade_ed78e5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user'], name='collections_user_id_b77b43_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['name'], name='collections_name_2c2ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_by'], name='images_uploade_6bd8cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionimage',
            unique_together={('collection', 'image')},
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['user'], name='image_inter_user_id_2d6b44_idx'),
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['image'], name='image_inter_image_i_04c080_idx'),
        ),
        migrations.AddIndex(
            model_name='imageinteraction',
            index=models.Index(fields=['external_image_id'], name='image_inter_externa_3885a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('image__isnull', False)), fields=('user', 'image', 'interaction_type'), name='unique_internal_image_interaction'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_image_id__isnull', False)), fields=('user', 'external_image_id', 'interaction_type'), name='unique_external_image_interaction'),
        ),
        migrations.AddConstraint(
            model_name='imageinteraction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_image_id__isnull', True), ('image__isnull', False)), models.Q(('external_image_id__isnull', False), ('image__isnull', True)), _connector='OR'), name='either_internal_or_external_image'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['user'], name='meta_commen_user_id_479cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['image'], name='meta_commen_image_i_213137_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['external_image_id'], name='meta_commen_externa_08e2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='metacomment',
            index=models.Index(fields=['created_at'], name='meta_commen_created_239f32_idx'),
        ),
        migrations.AddConstraint(
            model_name='metacomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_image_id__isnull', True), ('image__isnull', False)), models.Q(('external_image_id__isnull', False), ('image__isnull', True)), _connector='OR'), name='comment_either_internal_or_external_image'),
        ),
    ]
