# Generated by Django 5.1.7 on 2025-07-03 08:26

import common.apps.utils.user_directory._user_directory_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_ritual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_audio_path),
        ),
        migrations.AlterField(
            model_name='collection',
            name='music',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=common.apps.utils.user_directory._user_directory_path.user_music_path),
        ),
    ]
