# Generated by Django 5.1.7 on 2025-05-29 05:41

import common.apps.utils.generator._uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.UUIDField(default=common.apps.utils.generator._uuid.gen_uuid, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Order Confirmed'), (2, 'Order Confirmed'), (3, 'Payment Pending'), (4, 'Payment Confirmed'), (5, 'Order Packed/Ready to Pickup'), (6, 'Processing'), (7, 'Cancelled due to Merchant Inactivity.'), (8, 'Shipped'), (9, 'Out for Delivery'), (10, 'Delivery Reached Destination'), (11, 'Delivered'), (12, 'Return Initiated'), (13, 'Return Received'), (14, 'Refund Initiated'), (15, 'Refund Completed'), (16, 'Service Completed'), (17, 'Review Pending'), (18, 'Service Reviewed'), (19, 'Invoice Generated'), (20, 'Invoice Paid'), (21, 'Order Rejected'), (22, 'Failed Delivery')], default=1, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='gallery.image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_details',
            },
        ),
    ]
