from fastapi import APIRouter, File, UploadFile, Form
from fastapi.responses import JSONResponse
from typing import Optional
import os
import shutil
import tempfile
import sys
from deckoviz_ai.iconic_art._replicate_iconic_art import personalize_iconic_art_with_replicate
from utils.settings import get_settings

router = APIRouter()
settings = get_settings()

@router.post("/")
async def personalize_iconic_art(
    image_url: str = Form(...),
    face_image: Optional[UploadFile] = File(None),
    face_image_url: Optional[str] = Form(None),
    prompt: Optional[str] = Form(None),
    negative_prompt: Optional[str] = Form(None),
    style: Optional[str] = Form(None),
    num_inference_steps: Optional[int] = Form(None),
    guidance_scale: Optional[float] = Form(None),
    seed: Optional[int] = Form(None)
):
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            # Handle face image input (file or URL)
            if face_image is not None:
                face_path = os.path.join(tmpdir, face_image.filename)
                with open(face_path, "wb") as f:
                    shutil.copyfileobj(face_image.file, f)
                face_input = face_path
            elif face_image_url:
                face_input = face_image_url
            else:
                return JSONResponse(status_code=400, content={"error": "Either face_image file or face_image_url must be provided."})

            urls = personalize_iconic_art_with_replicate(
                image=image_url,
                face_image=face_input,
                prompt=prompt,
                negative_prompt=negative_prompt,
                style=style,
                num_inference_steps=num_inference_steps,
                guidance_scale=guidance_scale,
                seed=seed,
                api_token=settings.replicate_api_token
            )
            if not urls:
                print("No output URLs generated by Replicate. Returning error to client.", file=sys.stderr)
                return JSONResponse(status_code=500, content={"error": "No output generated by Replicate. Check your API key, input, and quota. See server logs for details."})
            return {"image_urls": urls}
    except Exception as e:
        print(f"Exception in personalize_iconic_art endpoint: {e}", file=sys.stderr)
        return JSONResponse(status_code=500, content={"error": str(e)}) 