from fastapi import APIRouter, File, UploadFile, Form, Depends
from fastapi.responses import JSONResponse
from typing import Optional
import os
import shutil
import tempfile
import sys
from deckoviz_ai.replicate_style_transfer._replicate_style_transfer import style_transfer_with_replicate
from utils.settings import get_settings
from utils.token import get_current_user
from schemas.user import User

router = APIRouter()
settings = get_settings()

@router.post("/")
async def replicate_style_transfer(
    image: Optional[UploadFile] = File(None),
    image_url: Optional[str] = Form(None),
    image_style: Optional[UploadFile] = File(None),
    image_style_url: Optional[str] = Form(None),
    seed: Optional[int] = Form(None),
    prompt: Optional[str] = Form(None),
    guidance_scale: Optional[float] = Form(None),
    style_strength: Optional[float] = Form(None),
    negative_prompt: Optional[str] = Form(None),
    structure_strength: Optional[float] = Form(None),
    num_inference_steps: Optional[int] = Form(None),
    current_user: User = Depends(get_current_user)
):
    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            # Handle image input (file or URL)
            if image is not None:
                image_path = os.path.join(tmpdir, image.filename)
                with open(image_path, "wb") as f:
                    shutil.copyfileobj(image.file, f)
                image_input = image_path
            elif image_url:
                image_input = image_url
            else:
                return JSONResponse(status_code=400, content={"error": "Either image file or image_url must be provided."})

            # Handle style image input (file or URL)
            if image_style is not None:
                style_path = os.path.join(tmpdir, image_style.filename)
                with open(style_path, "wb") as f:
                    shutil.copyfileobj(image_style.file, f)
                style_input = style_path
            elif image_style_url:
                style_input = image_style_url
            else:
                return JSONResponse(status_code=400, content={"error": "Either image_style file or image_style_url must be provided."})

            urls = style_transfer_with_replicate(
                image=image_input,
                image_style=style_input,
                output_dir=tmpdir,
                seed=seed,
                prompt=prompt,
                guidance_scale=guidance_scale,
                style_strength=style_strength,
                negative_prompt=negative_prompt,
                structure_strength=structure_strength,
                num_inference_steps=num_inference_steps,
                api_token=settings.replicate_api_token
            )
            if not urls:
                print("No output URLs generated by Replicate. Returning error to client.", file=sys.stderr)
                return JSONResponse(status_code=500, content={"error": "No output generated by Replicate. Check your API key, input, and quota. See server logs for details."})
            return {"image_urls": urls}
    except Exception as e:
        print(f"Exception in replicate_style_transfer endpoint: {e}", file=sys.stderr)
        return JSONResponse(status_code=500, content={"error": str(e)})