from fastapi import APIRouter,Depends
from deckoviz_ai.style_transfer import StyleTransferRequest,ImageStyleTransferAgent        
from fastapi import File, UploadFile
from runware import Runware,IImageInference
import base64
import os
from dotenv import load_dotenv
from utils.token import get_current_user
from schemas.user import User

load_dotenv()


router = APIRouter()


@router.post("/")
async def style_transfer(image: UploadFile = File(...), req: StyleTransferRequest = Depends(), current_user: User = Depends(get_current_user)):
    try:

        # Get the prompt generated by agent before passing it to the model
        req.image_base64 = image.file.read()
        req.image_base64 = base64.b64encode(req.image_base64).decode('utf-8')
        agent = ImageStyleTransferAgent()
        result = await agent.process_style_transfer(req)
        
        # Initialize Runware
        runware = Runware(api_key=os.getenv("RUNWARE_API_KEY"))
        await runware.connect()
        
        request_image = IImageInference(
                positivePrompt=result.styled_image_prompt,
                model="civitai:101055@128078",
                numberResults=1,
                negativePrompt=result.processing_notes,
                height=req.height,
                seedImage=req.image_base64,
                width=req.width,
          )
        images = await runware.imageInference(requestImage=request_image)
        return images
    except Exception as e:
        return {"error": str(e)}
