from fastapi import APIRouter,Depends
from deckoviz_ai.style_transfer import StyleTransferRequest,ImageStyleTransferAgent,StyleTransferResult        
from fastapi import File, UploadFile
import base64
import os
from google import genai
from google.genai import types
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()


@router.post("/")
async def style_transfer(image: UploadFile = File(...), req: StyleTransferRequest = Depends()):
    try:

        # Get the prompt generated by agent before passing it to the model
        req.image_base64 = image.file.read()
        req.image_base64 = base64.b64encode(req.image_base64).decode('utf-8')
        agent = ImageStyleTransferAgent()
        result = await agent.process_style_transfer(req)

        # Get the image generated by model
        response = genai.Client(api_key=os.getenv("GOOGLE_API_KEY")).models.generate_content(
                model="gemini-2.0-flash-preview-image-generation",
                contents=[result.styled_image_prompt, image.file.read()],
                config=types.GenerateContentConfig(
                response_modalities=['TEXT', 'IMAGE']
            )
        )
        # Extract and convert image from response
        for part in response.candidates[0].content.parts:
            if part.inline_data is not None:
                base64_str = base64.b64encode(part.inline_data.data).decode('utf-8')
                result.generated_image = base64_str
        return result 
    except Exception as e:
        result.error_message = str(e)
        return result
